In [24]:
import numpy as np

### Задание_1

In [27]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [28]:
mean_a = np.array(a.mean(axis=0))
mean_a

array([2. , 8.4])

### Задание_2

In [30]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание_3

In [43]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1] )
a_centered_sp

8.0

In [45]:
size = a.shape
answer = a_centered_sp/(size[0]-1)
answer

2.0

### Задание_4

In [47]:
b = np.cov(a.T)
b[0,1]

2.0