In [2]:
import numpy as np
import pandas as pd

#### Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [11]:
a = np.array(np.arange(start=12, stop=24, step=1))
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [16]:
a1=a.reshape(2, 6)
a2=a.reshape(3, 4)
a3=a.reshape(6, 2)
a4=a.reshape(4, 3)
a5=a.reshape(12, 1)

print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [22]:
a1=a.reshape(2, -1)
a2=a.reshape(3, -1)
a3=a.reshape(-1, 2)
a4=a.reshape(-1, 3)
a5=a.reshape(12, -1)

print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


#### Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нет, такой массив является двумерный.

#### Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [112]:
a = np.random.sample((3,4))
a

array([[0.12203823, 0.49517691, 0.03438852, 0.9093204 ],
       [0.25877998, 0.66252228, 0.31171108, 0.52006802],
       [0.54671028, 0.18485446, 0.96958463, 0.77513282]])

In [113]:
a.size

12

In [115]:
A = a.flatten()
A

array([0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998,
       0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446,
       0.96958463, 0.77513282])

In [116]:
A.size

12

#### Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [49]:
a = np.arange(start=20, stop=0, step=-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [53]:
b = a.reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

Массив а - одномерный, массив b - двумерный

#### Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [79]:
a = np.zeros((3, 2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [80]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [83]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [84]:
v.size

10

#### Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [88]:
a = np.arange(0, 12, 1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [89]:
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [90]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [92]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [93]:
d = np.linalg.det(B)
d

0.0

Нельзя посчитать обратную матрицу для матрицы В, так как ее определитель равен 0

#### Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [95]:
np.random.seed(42)

#### Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [99]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  1,  3,  8, 11, 13,  1,  9,  8,  9,  4,  1,  3, 11, 14, 11])

#### Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [100]:
C = c.reshape(4,4)
C

array([[ 6,  1,  3,  8],
       [11, 13,  1,  9],
       [ 8,  9,  4,  1],
       [ 3, 11, 14, 11]])

In [102]:
D = (C * 10) + B
D

array([[ 65,  24,  53, 112],
       [124, 180,  96, 212],
       [103, 176, 189, 222],
       [ 62, 232, 352, 412]])

In [103]:
d = np.linalg.det(D)
d

171262000.00000015

In [104]:
r = np.linalg.matrix_rank(D)
r

4

In [105]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 1.03443846e-02, -5.29948266e-03,  1.42261564e-02,
        -7.75069776e-03],
       [-1.41030701e-02,  7.06928566e-03,  4.01490115e-04,
        -2.00861837e-05],
       [ 1.14818232e-03, -1.24464271e-02,  1.56770329e-02,
        -2.35498826e-03],
       [ 5.40388411e-03,  7.45057281e-03, -1.57608810e-02,
         5.61689108e-03]])

#### Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [106]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 1.]])

In [110]:
E = np.where(D_inv, B, C)
E

array([[  5,   1,  23,   8],
       [ 11,  50,  86,   9],
       [ 23,   9, 149,   1],
       [ 32, 122,  14, 302]])